default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("POSTGRES_HOST") { "db" } %>
  username: <%= ENV.fetch("POSTGRES_USER") { "postgres" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "password" } %>


development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: ntnghia13
  password: Panda2905@
  host: 127.0.0.1
  port: 5433
  database: e_commerce_back_end_production


test:
  <<: *default
  database: e_commerce_back_end_test
  username: ntnghia13
  password: Panda2905@
  host: localhost

staging:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { "e_commerce_back_end_staging" } %>

production:
  <<: *default
  database: e_commerce_back_end_production
  password: <%= ENV["E_COMMERCE_BACK_END_DATABASE_PASSWORD"] %>