default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("POSTGRES_HOST") { "db" } %>
  username: <%= ENV.fetch("POSTGRES_USER") { "postgres" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "password" } %>

development:
  <<: *default
  database: e_commerce_back_end_development
  host: localhost

test:
  <<: *default
  database: e_commerce_back_end_test
  host: localhost

staging:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { "e_commerce_back_end_staging" } %>

production:
  <<: *default
  database: e_commerce_back_end_production
  password: <%= ENV["E_COMMERCE_BACK_END_DATABASE_PASSWORD"] %>